// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: state.proto

package keychain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KindState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         uint64                 `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	Round         uint32                 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KindState) Reset() {
	*x = KindState{}
	mi := &file_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KindState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KindState) ProtoMessage() {}

func (x *KindState) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KindState.ProtoReflect.Descriptor instead.
func (*KindState) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{0}
}

func (x *KindState) GetLevel() uint64 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *KindState) GetRound() uint32 {
	if x != nil {
		return x.Round
	}
	return 0
}

type KeyState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Index by SING_KIND numeric value (0x11,0x12,0x13).
	ByKind        map[int32]*KindState `protobuf:"bytes,1,rep,name=by_kind,json=byKind,proto3" json:"by_kind,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyState) Reset() {
	*x = KeyState{}
	mi := &file_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyState) ProtoMessage() {}

func (x *KeyState) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyState.ProtoReflect.Descriptor instead.
func (*KeyState) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{1}
}

func (x *KeyState) GetByKind() map[int32]*KindState {
	if x != nil {
		return x.ByKind
	}
	return nil
}

var File_state_proto protoreflect.FileDescriptor

const file_state_proto_rawDesc = "" +
	"\n" +
	"\vstate.proto\x12\bkeychain\"7\n" +
	"\tKindState\x12\x14\n" +
	"\x05level\x18\x01 \x01(\x04R\x05level\x12\x14\n" +
	"\x05round\x18\x02 \x01(\rR\x05round\"\x93\x01\n" +
	"\bKeyState\x127\n" +
	"\aby_kind\x18\x01 \x03(\v2\x1e.keychain.KeyState.ByKindEntryR\x06byKind\x1aN\n" +
	"\vByKindEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.keychain.KindStateR\x05value:\x028\x01B\x15Z\x13./keychain;keychainb\x06proto3"

var (
	file_state_proto_rawDescOnce sync.Once
	file_state_proto_rawDescData []byte
)

func file_state_proto_rawDescGZIP() []byte {
	file_state_proto_rawDescOnce.Do(func() {
		file_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_state_proto_rawDesc), len(file_state_proto_rawDesc)))
	})
	return file_state_proto_rawDescData
}

var file_state_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_state_proto_goTypes = []any{
	(*KindState)(nil), // 0: keychain.KindState
	(*KeyState)(nil),  // 1: keychain.KeyState
	nil,               // 2: keychain.KeyState.ByKindEntry
}
var file_state_proto_depIdxs = []int32{
	2, // 0: keychain.KeyState.by_kind:type_name -> keychain.KeyState.ByKindEntry
	0, // 1: keychain.KeyState.ByKindEntry.value:type_name -> keychain.KindState
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_state_proto_init() }
func file_state_proto_init() {
	if File_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_state_proto_rawDesc), len(file_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_state_proto_goTypes,
		DependencyIndexes: file_state_proto_depIdxs,
		MessageInfos:      file_state_proto_msgTypes,
	}.Build()
	File_state_proto = out.File
	file_state_proto_goTypes = nil
	file_state_proto_depIdxs = nil
}
